# Generated by Django 6.0 on 2025-12-21 17:42

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Aircraft Category',
                'verbose_name_plural': 'Aircraft Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FleetPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Fleet Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.TextField(blank=True)),
                ('full_description', wagtail.fields.RichTextField(blank=True)),
                ('passengers', models.IntegerField(default=8, help_text='Maximum passengers')),
                ('range_nm', models.IntegerField(default=3000, help_text='Range in nautical miles')),
                ('speed_knots', models.IntegerField(default=450, help_text='Max speed in knots')),
                ('baggage_capacity', models.CharField(blank=True, help_text='e.g. 120 cu ft', max_length=100)),
                ('cabin_height', models.CharField(blank=True, max_length=50)),
                ('cabin_width', models.CharField(blank=True, max_length=50)),
                ('cabin_length', models.CharField(blank=True, max_length=50)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Starting hourly rate in USD', max_digits=10, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('interior_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aircraft', to='fleet.aircraftcategory')),
            ],
            options={
                'verbose_name': 'Aircraft',
                'verbose_name_plural': 'Aircraft',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AircraftDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='fleet.aircraft')),
            ],
            options={
                'verbose_name': 'Aircraft Detail Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
