# Generated by Django 6.0 on 2025-12-21 17:42

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 5), ('fleet_highlight', 9), ('memberships', 17), ('services', 22), ('image_text', 26), ('experience', 28), ('safety_certifications', 33), ('cta', 35)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main headline', 'max_length': 200}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 300, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Book Your Flight', 'max_length': 50}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('headline', 1), ('subheadline', 2), ('cta_text', 3), ('show_flight_picker', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'DISCOVER OUR FLEET', 'max_length': 100}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 8: ('wagtail.blocks.TextBlock', (), {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('section_subtitle', 6), ('section_title', 7), ('section_description', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'default': 'Memberships', 'max_length': 200}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 12: ('wagtail.blocks.TextBlock', (), {}), 13: ('wagtail.blocks.CharBlock', (), {'default': 'View membership', 'max_length': 50}), 14: ('wagtail.blocks.URLBlock', (), {'required': False}), 15: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 11), ('description', 12), ('link_text', 13), ('link_url', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {}), 17: ('wagtail.blocks.StructBlock', [[('section_title', 10), ('section_description', 8), ('cards', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'SERVICES', 'max_length': 100}), 19: ('wagtail.blocks.CharBlock', (), {'default': 'Our solutions are different', 'max_length': 200}), 20: ('wagtail.blocks.StructBlock', [[('title', 11), ('description', 12), ('image', 0)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {}), 22: ('wagtail.blocks.StructBlock', [[('section_subtitle', 18), ('section_title', 19), ('section_description', 8), ('services', 21)]], {}), 23: ('wagtail.blocks.RichTextBlock', (), {}), 24: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 25: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Image Left'), ('right', 'Image Right')]}), 26: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 7), ('content', 23), ('link_text', 24), ('link_url', 14), ('image_position', 25)]], {}), 27: ('wagtail.blocks.CharBlock', (), {'default': 'THE BEST EXPERIENCE', 'max_length': 100}), 28: ('wagtail.blocks.StructBlock', [[('section_subtitle', 27), ('title', 7), ('description', 12), ('image', 0), ('link_text', 24), ('link_url', 14)]], {}), 29: ('wagtail.blocks.CharBlock', (), {'default': 'SAFETY AND CERTIFICATION', 'max_length': 100}), 30: ('wagtail.blocks.CharBlock', (), {'default': 'Commitment to safety', 'max_length': 200}), 31: ('wagtail.blocks.StructBlock', [[('name', 11), ('logo', 0)]], {}), 32: ('wagtail.blocks.ListBlock', (31,), {}), 33: ('wagtail.blocks.StructBlock', [[('section_subtitle', 29), ('section_title', 30), ('section_description', 8), ('certifications', 32)]], {}), 34: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 35: ('wagtail.blocks.StructBlock', [[('background_image', 34), ('title', 7), ('button_text', 3)]], {})})),
            ],
            options={
                'verbose_name': 'Home Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='FlyMex Aero', max_length=100)),
                ('phone_number', models.CharField(default='+52 55 4601 1670', max_length=50)),
                ('email', models.EmailField(default='info@flymex.aero', max_length=254)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('footer_text', models.TextField(blank=True, default='FlyMex - Flying private made simple')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
