# Generated by Django 6.0 on 2025-12-22 15:06

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('body', wagtail.fields.StreamField([('image_text', 6), ('cta', 9)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Image Left'), ('right', 'Image Right')]}), 6: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('content', 2), ('link_text', 3), ('link_url', 4), ('image_position', 5)]], {}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Book Your Flight', 'max_length': 50}), 9: ('wagtail.blocks.StructBlock', [[('background_image', 7), ('title', 1), ('button_text', 8)]], {})})),
            ],
            options={
                'verbose_name': 'Contact Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ExperiencePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('image_text', 6), ('services', 14), ('experience', 16), ('safety_certifications', 21), ('cta', 24)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Image Left'), ('right', 'Image Right')]}), 6: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('content', 2), ('link_text', 3), ('link_url', 4), ('image_position', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'SERVICES', 'max_length': 100}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Our solutions are different', 'max_length': 200}), 9: ('wagtail.blocks.TextBlock', (), {'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 11: ('wagtail.blocks.TextBlock', (), {}), 12: ('wagtail.blocks.StructBlock', [[('title', 10), ('description', 11), ('image', 0)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {}), 14: ('wagtail.blocks.StructBlock', [[('section_subtitle', 7), ('section_title', 8), ('section_description', 9), ('services', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'default': 'THE BEST EXPERIENCE', 'max_length': 100}), 16: ('wagtail.blocks.StructBlock', [[('section_subtitle', 15), ('title', 1), ('description', 11), ('image', 0), ('link_text', 3), ('link_url', 4)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'default': 'SAFETY AND CERTIFICATION', 'max_length': 100}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Commitment to safety', 'max_length': 200}), 19: ('wagtail.blocks.StructBlock', [[('name', 10), ('logo', 0)]], {}), 20: ('wagtail.blocks.ListBlock', (19,), {}), 21: ('wagtail.blocks.StructBlock', [[('section_subtitle', 17), ('section_title', 18), ('section_description', 9), ('certifications', 20)]], {}), 22: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 23: ('wagtail.blocks.CharBlock', (), {'default': 'Book Your Flight', 'max_length': 50}), 24: ('wagtail.blocks.StructBlock', [[('background_image', 22), ('title', 1), ('button_text', 23)]], {})})),
            ],
            options={
                'verbose_name': 'Experience Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='GenericPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 5), ('image_text', 11), ('services', 19), ('experience', 21), ('safety_certifications', 26), ('cta', 28)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main headline', 'max_length': 200}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 300, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Book Your Flight', 'max_length': 50}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('headline', 1), ('subheadline', 2), ('cta_text', 3), ('show_flight_picker', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 7: ('wagtail.blocks.RichTextBlock', (), {}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 9: ('wagtail.blocks.URLBlock', (), {'required': False}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Image Left'), ('right', 'Image Right')]}), 11: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 6), ('content', 7), ('link_text', 8), ('link_url', 9), ('image_position', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'SERVICES', 'max_length': 100}), 13: ('wagtail.blocks.CharBlock', (), {'default': 'Our solutions are different', 'max_length': 200}), 14: ('wagtail.blocks.TextBlock', (), {'required': False}), 15: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 16: ('wagtail.blocks.TextBlock', (), {}), 17: ('wagtail.blocks.StructBlock', [[('title', 15), ('description', 16), ('image', 0)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {}), 19: ('wagtail.blocks.StructBlock', [[('section_subtitle', 12), ('section_title', 13), ('section_description', 14), ('services', 18)]], {}), 20: ('wagtail.blocks.CharBlock', (), {'default': 'THE BEST EXPERIENCE', 'max_length': 100}), 21: ('wagtail.blocks.StructBlock', [[('section_subtitle', 20), ('title', 6), ('description', 16), ('image', 0), ('link_text', 8), ('link_url', 9)]], {}), 22: ('wagtail.blocks.CharBlock', (), {'default': 'SAFETY AND CERTIFICATION', 'max_length': 100}), 23: ('wagtail.blocks.CharBlock', (), {'default': 'Commitment to safety', 'max_length': 200}), 24: ('wagtail.blocks.StructBlock', [[('name', 15), ('logo', 0)]], {}), 25: ('wagtail.blocks.ListBlock', (24,), {}), 26: ('wagtail.blocks.StructBlock', [[('section_subtitle', 22), ('section_title', 23), ('section_description', 14), ('certifications', 25)]], {}), 27: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 28: ('wagtail.blocks.StructBlock', [[('background_image', 27), ('title', 6), ('button_text', 3)]], {})})),
            ],
            options={
                'verbose_name': 'Generic Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
